default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1
  port: 3308

development:
  <<: *default
  database: dalilainventory_development

test:
  <<: *default
  database: dalilainventory_test

production:
  <<: *default
  database: dalilainventory_production
